### PR TITLE
Use internal renovate config

### PR DESCRIPTION
**Pull request by jkempster34**
The internal renovate config automatically merges minor updates compared to the standard configuration which only merges patches.

### CODE REVIEW

**Comment by jkempster34** [comment]
@yndajas Can you help with this one please? Is there a reason we didn;t opt to use the internal config for the repo before?

**Comment by yndajas** [comment]
> @yndajas Can you help with this one please? Is there a reason we didn't opt to use the internal config for the repo before?

Yep - this is meant to emulate a client project, where we'd only merge patch updates automatically (if anything)

**Comment by jdudley1123** [comment]
I'm not convinced that emulating a client project in this regard is helpful here. What value are we getting?

**Comment by yndajas** [comment]
> I'm not convinced that emulating a client project in this regard is helpful here. What value are we getting?

I thought the point of the DfSSETA projects was for them to be models of client-like work, but I suppose the value of following client standards to the T is lower than in the template repos, which should be ready to use as templates as and when

**Comment by jdudley1123** [comment]
They're useful as a model for things like use of the Gov.UK design system and building typical flows, but I don't think we need to extend that to package management. Unless @edavey has any objections, I think lets use the internal config.

**Review by lozette — APPROVED** [review]
I'm going to approve this as I think it's OK to use the internal config, especially given time constraints on merging minor versions.

**Pull request merged**
